import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Trash, CheckSquare } from '@phosphor-icons/react';
import { useDebounce } from '../hooks/useDebounce';
import type { Memory, Todo, RAGSearchResult } from '../types';

interface NoteDetailModalProps {
  isOpen: boolean;
  onClose: () => void;
  item: Memory | Todo | { document: RAGSearchResult['document']; isCitation?: boolean } | null;
  type: 'memory' | 'todo';
  onUpdate: (id: string, data: any) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
  onConvert?: (item: Memory) => Promise<void>;
}

export default function NoteDetailModal({
  isOpen,
  onClose,
  item,
  type,
  onUpdate,
  onDelete,
  onConvert,
}: NoteDetailModalProps) {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);
  const contentRef = useRef<HTMLTextAreaElement>(null);
  const titleRef = useRef<HTMLInputElement>(null);

  const [summary, setSummary] = useState(''); // For displaying summary separately

  useEffect(() => {
    if (item) {
      if ('document' in item) {
        // Citation - read-only
        setTitle(item.document.title || item.document.content.substring(0, 50));
        setContent(item.document.content || '');
        setSummary('');
      } else if (type === 'memory') {
        const memory = item as Memory;
        setTitle(''); // No title field for memories
        setContent(memory.content || '');
        setSummary(memory.summary || ''); // Summary displayed separately at bottom
      } else {
        const todo = item as Todo;
        setTitle(todo.title || '');
        setContent(todo.description || '');
        setSummary('');
      }
      setHasChanges(false);
    }
  }, [item, type]);

  // Focus content when modal opens
  useEffect(() => {
    if (isOpen && item && !('document' in item)) {
      setTimeout(() => {
        if (type === 'memory' && contentRef.current) {
          contentRef.current.focus();
        } else if (type === 'todo' && titleRef.current) {
          titleRef.current.focus();
        }
      }, 100);
    }
  }, [isOpen, item, type]);

  const debouncedTitle = useDebounce(title, 300);
  const debouncedContent = useDebounce(content, 300);

  useEffect(() => {
    if (!item || !isOpen || isSaving) return;
    if ('document' in item) return; // Citations are read-only

    const originalTitle = type === 'todo' 
      ? (item as Todo).title || ''
      : '';
    const originalContent = type === 'memory'
      ? (item as Memory).content || ''
      : (item as Todo).description || '';

    // For memories, only check content changes (summary is read-only)
    // For todos, check both title and content
    const hasContentChange = debouncedContent !== originalContent;
    const hasTitleChange = type === 'todo' && debouncedTitle !== originalTitle;

    if (hasContentChange || hasTitleChange) {
      setHasChanges(true);
      handleAutoSave();
    }
  }, [debouncedTitle, debouncedContent, item, type, isOpen]);

  const handleAutoSave = async () => {
    if (!item || 'document' in item) return;
    if (!hasChanges) return;

    setIsSaving(true);
    try {
      if (type === 'memory') {
        // For memories, only update content (summary is auto-generated by backend)
        await onUpdate((item as Memory).id, {
          content: debouncedContent,
        });
      } else {
        await onUpdate((item as Todo).id, {
          title: debouncedTitle,
          description: debouncedContent || null,
        });
      }
      setHasChanges(false);
    } catch (error) {
      console.error('Auto-save failed:', error);
    } finally {
      setIsSaving(false);
    }
  };

  const handleSave = async () => {
    if (!item || 'document' in item) return;
    
    setIsSaving(true);
    try {
      if (type === 'memory') {
        await onUpdate((item as Memory).id, {
          content: content.trim(),
          summary: title.trim() || undefined,
        });
      } else {
        await onUpdate((item as Todo).id, {
          title: title.trim(),
          description: content.trim() || null,
        });
      }
      setHasChanges(false);
    } catch (error) {
      console.error('Save failed:', error);
    } finally {
      setIsSaving(false);
    }
  };

  const handleClose = async () => {
    // Auto-save on close if there are changes
    if (!item || 'document' in item) {
      onClose();
      return;
    }
    
    if (hasChanges) {
      await handleSave();
    }
    onClose();
  };

  const handleDelete = async () => {
    if (!item || 'document' in item) return;
    if (window.confirm('Are you sure you want to delete this item?')) {
      await onDelete((item as Memory | Todo).id);
      onClose();
    }
  };

  const handleConvert = async () => {
    if (!item || type !== 'memory' || 'document' in item) return;
    if (onConvert) {
      await onConvert(item as Memory);
      onClose();
    }
  };

  if (!isOpen || !item) return null;

  const isCitation = 'document' in item;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm"
        onClick={handleClose}
      >
        <motion.div
          initial={{ scale: 0.95, opacity: 0, y: 20 }}
          animate={{ scale: 1, opacity: 1, y: 0 }}
          exit={{ scale: 0.95, opacity: 0, y: 20 }}
          transition={{ duration: 0.2, ease: [0.4, 0, 0.2, 1] }}
          onClick={(e) => e.stopPropagation()}
          className="bg-white dark:bg-gray-900 rounded-lg shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col"
          style={{
            boxShadow: '0 8px 16px rgba(0, 0, 0, 0.15), 0 0 0 1px rgba(0, 0, 0, 0.05)',
          }}
        >
          {/* Content Area - Google Keep style */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Title - Only for todos and citations */}
            {(type === 'todo' || isCitation) && (
              <div className="px-6 pt-6 pb-3">
                {isCitation ? (
                  <h2 className="text-lg font-bold text-gray-900 dark:text-white">
                    {title || 'Untitled'}
                  </h2>
                ) : (
                  <input
                    ref={titleRef}
                    type="text"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="Title"
                    className="w-full text-lg font-medium bg-transparent border-none outline-none text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 resize-none"
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        contentRef.current?.focus();
                      }
                    }}
                  />
                )}
              </div>
            )}

            {/* Content textarea */}
            <div className="flex-1 px-6 py-4 overflow-y-auto">
              {isCitation ? (
                <div className="text-sm text-gray-900 dark:text-white whitespace-pre-wrap leading-relaxed">
                  {content}
                </div>
              ) : (
                <textarea
                  ref={contentRef}
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  placeholder={type === 'memory' ? 'Start typing your memory...' : 'Start typing...'}
                  className="w-full min-h-[250px] text-sm bg-transparent border-none outline-none text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 resize-none"
                  style={{ 
                    fontFamily: 'inherit',
                    lineHeight: '1.6',
                  }}
                />
              )}
            </div>

            {/* Summary - At bottom, grey, multiline, read-only (only for memories) */}
            {type === 'memory' && !isCitation && summary && (
              <div className="px-6 pb-4 pt-2 border-t border-gray-100 dark:border-gray-800">
                <div className="text-xs text-gray-500 dark:text-gray-400 whitespace-pre-wrap leading-relaxed">
                  {summary}
                </div>
              </div>
            )}

            {/* Footer - Google Keep style with actions */}
            <div className="px-6 py-3 flex items-center justify-between border-t border-gray-100 dark:border-gray-800">
              {/* Action buttons on left */}
              <div className="flex items-center gap-2">
                {!isCitation && type === 'memory' && onConvert && (
                  <button
                    onClick={handleConvert}
                    className="p-2 hover:bg-gray-100 dark:hover:bg-gray-800 rounded transition-colors"
                    title="Convert to Todo"
                  >
                    <CheckSquare size={18} weight="regular" className="text-gray-600 dark:text-gray-400" />
                  </button>
                )}
                {!isCitation && (
                  <button
                    onClick={handleDelete}
                    className="p-2 hover:bg-red-50 dark:hover:bg-red-900/20 rounded transition-colors"
                    title="Delete"
                  >
                    <Trash size={18} weight="regular" className="text-red-600 dark:text-red-400" />
                  </button>
                )}
                {isSaving && (
                  <span className="text-xs text-gray-500 dark:text-gray-400 ml-2">Saving...</span>
                )}
                {hasChanges && !isSaving && !isCitation && (
                  <span className="text-xs text-primary-600 dark:text-primary-400 ml-2">Unsaved changes</span>
                )}
              </div>
              
              {/* Save button on right */}
              <button
                type="button"
                onClick={handleClose}
                disabled={isSaving}
                className="px-5 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isSaving ? 'Saving...' : 'Save'}
              </button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

